//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Delivery_System.CommonEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMSEntities : DbContext
    {
        public DMSEntities()
            : base("name=DMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CarConfiguration> CarConfigurations { get; set; }
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<CarPart> CarParts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<ExteriorColor> ExteriorColors { get; set; }
        public virtual DbSet<InteriorColor> InteriorColors { get; set; }
        public virtual DbSet<NVDO> NVDOes { get; set; }
        public virtual DbSet<NVSO> NVSOes { get; set; }
        public virtual DbSet<NVSQ> NVSQs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<ShowroomInformation> ShowroomInformations { get; set; }
        public virtual DbSet<DMSUser> DMSUsers { get; set; }
    }
}
