//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Delivery_System.CommonEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowroomInformation
    {
        public int Id { get; set; }
        public string companyname { get; set; }
        public string address { get; set; }
        public string representative { get; set; }
        public string bank { get; set; }
        public string accountno { get; set; }
    }
}
